micronaut:
  application:
    name: accountsData
datasources:
  default:
    url: jdbc:mysql://mysqlbi.public.nexmo.io:3306/config
    driverClassName: com.mysql.cj.jdbc.Driver

redact:
  api:
    baseUrl: http://10.112.78.124:3322
